services:
  db:
    container_name: game-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    container_name: game-gateway
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    env_file:
      - services/gateway/.env
    ports:
      - "3000:3000"
    volumes:
      - ./services/gateway/:/usr/src/app/
      - /usr/src/app/node_modules
    command: pnpm run dev
#    command: tail -f /etc/hosts


  engine:
    container_name: engine-gateway
    build:
      context: .
      dockerfile: services/engine/Dockerfile
    env_file:
      - services/engine/.env
    volumes:
      - ./services/engine/:/usr/src/app/
      - /usr/src/app/node_modules
    command: pnpm run dev

  auth:
    container_name: game-auth
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - services/auth/.env
    volumes:
      - ./services/auth/:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    command: pnpm run dev

  profile:
    container_name: game-profile
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - services/profile/.env
    volumes:
      - ./services/profile/:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    command: pnpm run dev

#  ship:
#    container_name: game-ship
#    build:
#      context: .
#      dockerfile: services/ship/Dockerfile
#    env_file:
#      - services/ship/.env
#    volumes:
#      - ./services/ship/:/usr/src/app/
#      - /usr/src/app/node_modules
#    depends_on:
#      kafka:
#        condition: service_healthy
#      db:
#        condition: service_started
#    command: pnpm run dev

  asteroid:
    container_name: game-asteroid
    build:
      context: .
      dockerfile: services/asteroid/Dockerfile
    env_file:
      - services/asteroid/.env
    volumes:
      - ./services/asteroid/:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    command: pnpm run dev

#  mail:
#    container_name: game-mail
#    build:
#      context: .
#      dockerfile: services/mail/Dockerfile
#    env_file:
#      - services/mail/.env
#    volumes:
#      - ./services/mail/:/usr/src/app/
#      - /usr/src/app/node_modules
#    command: pnpm run dev

  kafka:
    container_name: game-kafka
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "kraft-cluster-001"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    container_name: game-mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_WEBROOT : "/mailpit/"
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_AUTH: "login:pass"
      MP_MAX_MESSAGES: 5000
    volumes:
      - /data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  kafka_data: