[databases]
postgres      = host=postgres port=5432 dbname=postgres      user=postgres
auth          = host=postgres port=5432 dbname=auth          user=postgres
profile       = host=postgres port=5432 dbname=profile       user=postgres
battle        = host=postgres port=5432 dbname=battle        user=postgres
engine        = host=postgres port=5432 dbname=engine        user=postgres
orchestration = host=postgres port=5432 dbname=orchestration user=postgres
streaming     = host=postgres port=5432 dbname=streaming     user=postgres
*             = host=postgres port=5432                      user=postgres


[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

# пул соединений
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 10
reserve_pool_size = 5
reserve_pool_timeout = 5

# логирование
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid

# таймауты
server_idle_timeout = 30
query_timeout = 60
